### ISSUE TITLE
Implement proper damage tracking

### ISSUE THREAD

**Issue by Ongy** [Ongy/waymonad#21]
The current damage tracking is very simple. It just tracks if an output has to be repainted and reuses the `wlroots` `needs_swap` flag on the output.

This should be done in more elegant ways.

- [x]  Get damage regions on commits
  - [x] WlrSurface
    - [x] WlrSubsurface
  - [x] XWayland children
  - [x] XdgShell popups
  - [x] WlShell popups
- [x] Actual track damage
  - [x] Use custom `needs_swap` to skip view redraw on pointer movement
  - [x] Use the `WlrBox` in `outApplyDamage`
- [x] Use damage in render-loop
  - [x] Only repaint if required (only swap otherwise)
  - [x] Use the scissor to limit repaint to damaged areas
    - [x] scissor surfaces properly
    - [x] scissor SSD properly
